export const copy = {
  "it": {
    "navHome": "Collezione",
    "aboutTitle": "Chi siamo",
    "aboutIntro": "Una storia di famiglia, una passione per l’abito. Da Napoli, dal 1989.",
    "aboutTeaser": "Una tradizione di famiglia. Un modo di essere.",
    "readStory": "La nostra storia",
    "footerSketchAlt": "Disegno a matita della facciata di uno spazio LAMURA",
    "skip": "Vai al contenuto",
    "home": "LAMURA — Home",
    "close": "Chiudi",
    "menu": "Menu",
    "navigation": "Navigazione principale",
    "navStory": "La nostra storia",
    "navCollection": "La collezione",
    "navContact": "Contatti",
    "heroTitle": "Classici da vivere.",
    "heroText": "Una tradizione di famiglia nata a Napoli. Tessuti ricercati e cura dei dettagli, per un’eleganza che si vive ogni giorno.",
    "explore": "Scopri LAMURA",
    "rhythm": "AL RITMO DELLA NATURA",
    "scroll": "Continua a scoprire",
    "storyLabel": "LA NOSTRA STORIA",
    "storyTitle": "Tutto comincia a Napoli.",
    "storyOne": "LAMURA nasce a Napoli nel 1989, da una tradizione di famiglia dedicata alla confezione di abiti.",
    "storyTwo": "La scelta dei tessuti e l’attenzione alle finiture guidano da sempre il nostro lavoro. Creiamo capi dal carattere essenziale, pensati per accompagnare la vita di ogni giorno.",
    "portraitAlt": "Una modella indossa un lungo cardigan blu davanti a una parete in pietra",
    "caption": "LAMURA — L’eleganza, con naturalezza",
    "fabricAlt": "Capi bianchi sospesi su uno stender in uno spazio essenziale",
    "craftLabel": "IL PIACERE DI VESTIRSI",
    "craftTitle": "Tessuti ricercati.\nLinee libere.",
    "craftText": "La mano di un tessuto, il movimento di un abito. Ogni dettaglio contribuisce al piacere di indossarlo: forme morbide e una cura che si sente, ogni giorno.",
    "discoverCollection": "Esplora la collezione",
    "wardrobeLabel": "IL GUARDAROBA",
    "wardrobeTitle": "Abiti da vivere.",
    "wardrobeText": "Tra natura e città,\nal proprio ritmo.",
    "viewLook": "Scopri il look",
    "philosophyLabel": "IL MONDO LAMURA",
    "philosophyTitle": "Il piacere di ritrovare\ni propri capi, ogni giorno.",
    "philosophyText": "Linee essenziali e dettagli curati.\nUn modo di vestire autentico, da sentire proprio.",
    "contactLabel": "PARLIAMONE",
    "contactTitle": "Restiamo in contatto.",
    "contactText": "Per informazioni sul brand o proposte di collaborazione, scrivici.",
    "write": "Scrivici",
    "telephone": "TELEFONO",
    "location": "ROMA, ITALIA",
    "backHome": "Torna alla home",
    "backTop": "Torna su",
    "dialogLabel": "Il look nel dettaglio",
    "askLook": "Chiedi informazioni sul look",
    "previous": "Precedente",
    "next": "Successivo",
    "language": "Lingua",
    "looks": [
      {
        "title": "Toni chiari",
        "description": "Strati leggeri e contrasti delicati, per un’eleganza disinvolta.",
        "alt": "Una modella con berretto beige, giacca scura e gonna chiara davanti a una parete in pietra"
      },
      {
        "title": "Sotto la pioggia",
        "description": "Un cardigan avvolgente e linee morbide, anche nei giorni di pioggia.",
        "alt": "Una modella con ombrello nero indossa un lungo cardigan grigio e pantaloni chiari"
      },
      {
        "title": "In città · Blu",
        "description": "Maglieria morbida e volumi rilassati, al ritmo della città.",
        "alt": "Look blu con berretto in maglia e pantaloni ampi"
      }
    ],
    "meta": "LAMURA, dal 1989. Una tradizione di famiglia nata a Napoli, tessuti ricercati e capi essenziali da vivere ogni giorno."
  },
  "en": {
    "navHome": "Collection",
    "aboutTitle": "About us",
    "aboutIntro": "A family story, a love of making clothes. Rooted in Naples since 1989.",
    "aboutTeaser": "A family tradition. A way of being.",
    "readStory": "Our story",
    "footerSketchAlt": "Pencil sketch of a LAMURA storefront",
    "skip": "Skip to content",
    "home": "LAMURA — Home",
    "close": "Close",
    "menu": "Menu",
    "navigation": "Main navigation",
    "navStory": "Our story",
    "navCollection": "Collection",
    "navContact": "Contact",
    "heroTitle": "Everyday, timeless.",
    "heroText": "Rooted in a Neapolitan family tradition. Considered fabrics and careful detailing, for a quietly elegant everyday wardrobe.",
    "explore": "Discover LAMURA",
    "rhythm": "A NATURAL RHYTHM",
    "scroll": "Explore below",
    "storyLabel": "OUR STORY",
    "storyTitle": "It begins in Naples.",
    "storyOne": "LAMURA began in Naples in 1989, with a family tradition of making clothes.",
    "storyTwo": "Our work has always been guided by the choice of fabric and attention to finishing. We create understated pieces with a distinct character, made to become part of everyday life.",
    "portraitAlt": "A model wearing a long navy cardigan against a stone wall",
    "caption": "LAMURA — Elegance, at ease",
    "fabricAlt": "White garments hanging from a rail in a minimal interior",
    "craftLabel": "THE ART OF EVERYDAY",
    "craftTitle": "Considered fabrics.\nEffortless shapes.",
    "craftText": "The feel of a fabric. The way a garment moves. Every detail shapes the experience of wearing it, with easy silhouettes and care you can feel.",
    "discoverCollection": "Explore the collection",
    "wardrobeLabel": "THE WARDROBE",
    "wardrobeTitle": "Clothes to live in.",
    "wardrobeText": "Between nature and the city,\nat your own pace.",
    "viewLook": "View look",
    "philosophyLabel": "THE LAMURA PHILOSOPHY",
    "philosophyTitle": "The pieces you return to,\ntime and again.",
    "philosophyText": "Timeless lines and thoughtful details.\nClothes that feel comfortable, natural, and entirely your own.",
    "contactLabel": "GET IN TOUCH",
    "contactTitle": "Let’s start a conversation.",
    "contactText": "For brand enquiries or collaborations, we’d love to hear from you.",
    "write": "Write to us",
    "telephone": "TELEPHONE",
    "location": "ROME, ITALY",
    "backHome": "Back to home",
    "backTop": "Back to top",
    "dialogLabel": "Look details",
    "askLook": "Enquire about this look",
    "previous": "Previous",
    "next": "Next",
    "language": "Language",
    "looks": [
      {
        "title": "Light tones",
        "description": "Light layers and subtle contrasts, worn with quiet confidence.",
        "alt": "A model in a beige beanie, dark jacket and light skirt against a stone wall"
      },
      {
        "title": "Rainy days",
        "description": "An enveloping cardigan and easy shapes for days under grey skies.",
        "alt": "A model holding a black umbrella, wearing a long grey cardigan and light trousers"
      },
      {
        "title": "In the city · Blue",
        "description": "Soft knitwear and relaxed proportions for days in the city.",
        "alt": "A navy outfit with a knitted beanie and wide-leg trousers"
      }
    ],
    "meta": "LAMURA, since 1989. A family clothing tradition from Naples, with considered fabrics and understated pieces for everyday life."
  }
};
